### ISSUE TITLE
cannot import name 'WordEmbCheckpointSaver' from 'gensim.models.callbacks' 

### ISSUE THREAD

**Issue by pritomsaha** [alex-tifrea/poincare_glove#11]
I am encountering this problem when running ./run_glove.h....

**Comment by ayushbits** [comment]
Hi @pritomsaha ,
I am facing the same problem. How did you solve this issue ?

**Comment by ayushbits** [comment]
Mentioning the solution for other users:

**Do not pre-install gensim library in your environment and remove if pre-installed.** 
and follow the installation instructions given in the repo.

**Comment by gullirg** [comment]
Hi @ayushbits, I followed the installation instructions given in the repo but I'm still getting the issue:

` ImportError: cannot import name 'WordEmbCheckpointSaver' from 'gensim.models.callbacks'`

Any idea of how to solve this?
