### ISSUE TITLE
cannot import name 'WordEmbCheckpointSaver' from 'gensim.models.callbacks'

### ISSUE THREAD

**Issue by fangguo1** [alex-tifrea/poincare_glove#3]
#### Description
I encountered this problem as 'cannot import name 'WordEmbCheckpointSaver' from 'gensim.models.callbacks''. Which gensim are you using? The latest gensim seems not having 'WordEmbCheckpointSaver' in callbacks.py

**Comment by Clarioooo** [comment]
Hi @fangguo1 ,
I met the same problem. Have you solved it?

> FileNotFoundError: [Errno 2] No such file or directory: '../msc_tifreaa/gensim/test/test_data/rare_word.txt'

> FileNotFoundError: [Errno 2] No such file or directory: '../models/glove/glove_baseline/glove_ep50_size100_lr0.05_vocab4000_vanilla_OPTadagrad_COOCCFUNClog_DISTFUNCcosh-dist-sq_bias'
And the gensim's version is 3.4.0
