### ISSUE TITLE
About Hypernymy score 

### ISSUE THREAD

**Issue by fangguo1** [alex-tifrea/poincare_glove#4]
Hi, I am following your paper **Poincare Glove: Hyperbolic Word Embedding**. In your paper, you mentioned the experiment of hypernym detection and hypernymy score detection, but I am not able to find the corresponding code for this part.  Did you upload this part? Thanks a lot!

**Comment by alex-tifrea** [comment]
Check out util_scripts/run_hypernymy_eval.sh

**Comment by Clarioooo** [comment]
Hi @fangguo1.
Could you please tell me how to solve

> FileNotFoundError: [Errno 2] No such file or directory: '../models/glove/glove_baseline/glove_ep50_size100_lr0.05_vocab4000_vanilla_OPTadagrad_COOCCFUNClog_DISTFUNCcosh-dist-sq_bias'

> FileNotFoundError: [Errno 2] No such file or directory: '../msc_tifreaa/gensim/test/test_data/rare_word.txt'
